///Auto-Generated By TemplateBaker///


using UnityEngine;
using UnityEditor;
namespace CHG.Editor.ScriptTemplates.Generated
{	public static class BakedScriptTemplates
	{
		[MenuItem("Assets/Create/Create Script By Templates/BehaviourScript", priority = 80)]
		static void CreateScript0()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/BehaviourScript.txt","NewBehaviourScript.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/Class", priority = 80)]
		static void CreateScript1()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/Class.txt","NewClass.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/EditorScript", priority = 80)]
		static void CreateScript2()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/EditorScript.txt","NewEditorScript.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/EditorWindowScript", priority = 80)]
		static void CreateScript3()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/EditorWindowScript.txt","NewEditorWindowScript.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/Enum", priority = 80)]
		static void CreateScript4()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/Enum.txt","NewEnum.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/FullSettedBehaviourScript", priority = 80)]
		static void CreateScript5()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/FullSettedBehaviourScript.txt","NewFullSettedBehaviourScript.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/Interface", priority = 80)]
		static void CreateScript6()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/Interface.txt","NewInterface.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/ScriptableObject", priority = 80)]
		static void CreateScript7()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/ScriptableObject.txt","NewScriptableObject.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/SegmentedBehaviourScript", priority = 80)]
		static void CreateScript8()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/SegmentedBehaviourScript.txt","NewSegmentedBehaviourScript.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/Struct", priority = 80)]
		static void CreateScript9()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/Struct.txt","NewStruct.cs");
		}
		[MenuItem("Assets/Create/Create Script By Templates/TriggerTaskScript", priority = 80)]
		static void CreateScript10()
		{
			ProjectWindowUtil.CreateScriptAssetFromTemplateFile("Assets/Settings/ScriptTemplates/TemplateFiles/TriggerTaskScript.txt","NewTriggerTaskScript.cs");
		}
	}
}